# Generated by Django 5.0.3 on 2024-03-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_clone", "0003_alter_tweet_tweet_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/tweets"),
        ),
    ]
