# Generated by Django 5.0.3 on 2024-03-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_clone", "0005_rename_profile_image_tweet_tweet_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile"),
        ),
    ]
